### ISSUE TITLE
Undefined behavior in _pop16

### ISSUE THREAD

**Issue by boomlinde** [ITotalJustice/6502#1]
return (_pop8(mos6502)) | (_pop8(mos6502) << 8);

The intended effect is that the expressions on both sides of `|` are evaluated in a particular order. However, `|` does not mark a sequence point, and the order they're actually evaluated in is undefined. Because `_pop8` has a side effect that affects subsequent calls, the function may return wrong-endian values.

I've not reviewed the entire codebase, but this is true also for other bitwise and arithmetic operators.

**Comment by ITotalJustice** [comment]
Hi, thank you for opening an issue on this. I didn't realise that the functions could be evaluated in any order! This would cause UB for `pop16` as you said but also `read16` and all indirect functions (`IND`, `INDX` and `INDY`) because `read()` can have side effects, for example unsetting a latched read (this happens if reading from the ppu registers if emulating the NES).

Very good find! I can fix this by creating a temp var storing the lo byte, then read the hi byte and shift (this is for pop16)
```
static unsigned short _pop16(struct MOS6502* mos6502) { /* lo byte, then, hi byte << 8 */
    const unsigned short value = _pop8(mos6502);
    return value | (_pop8(mos6502) << 8);
}
```

Do you know if this would ensure that the compiler would call the functions in this order?

**Comment by boomlinde** [comment]
Yep, that'll do the trick! Separate statements should always be (effectively) in sequence. I have a similar temporary workaround for now.

I found this while compiling with Watcom C. Good to know that read16 will have this issue as well, although that's less likely to affect me personally for now.

**Comment by ITotalJustice** [comment]
Hi, i've pushed a commit with the changes. I've checked through each function and i believe that i've changed all those that can cause side effects. Let me know if this fixes your issue

**Comment by boomlinde** [comment]
This works well, thanks! The change solves my issue.
